### ISSUE TITLE
To many redirects when trying to get favicon.ico [chrome]

### ISSUE THREAD

**Issue by Torbacka** [KeenRivals/bestmotherfucking.website#1]

**Comment by KeenRivals** [comment]
Thank you for the bug report! I never noticed this. It seems like it was an issue with how HTTP was being redirected to HTTPS. I was using Cloudflare's Flexible SSL in order to avoid setting up a TLS at my web host. It seems like this level of indirection was causing a redirect loop for files that should 404. 

I've set up TLS at my web host and removed the redirection goop from .htaccess in commit [bace680](https://github.com/KeenRivals/bestmotherfucking.website/commit/bace6805de15fbce8318eefc4328d5973a37d17b). This issue seems to be resolved now. Thank you again!
