### ISSUE TITLE
HTTP/2 does not require HTTPS

### ISSUE THREAD

**Issue by SatoMew** [KeenRivals/bestmotherfucking.website#34]
Contrary to what the website mentions, only web browsers *de facto* require HTTPS in their HTTP/2 implementations, [but HTTP/2 itself is unencrypted by default](https://http2.github.io/faq/#does-http2-require-encryption).

On the other hand, HTTP/3 does require encryption as TLS 1.3 was baked into the protocol itself.

**Comment by KeenRivals** [comment]
> currently no browser supports HTTP/2 unencrypted

In order to use HTTP/2 in the wild you _must_ use TLS. I don't think it's worth making the distinction on a meme website.

I look forward to advertising HTTP/3 on the site, but last I checked no one is implementing yet. I recently watched a talk by [Daniel Stenberg](https://youtu.be/Tj88nQb2SvI) where he discussed the status of the effort. In that talk he mentioned an August-ish launch date, but it seems like they missed that. Granted, the talk was in January.
