### ISSUE TITLE
HTTP/3

### ISSUE THREAD

**Issue by jtagcat** [KeenRivals/bestmotherfucking.website#49]
> It’s also required for HTTP/2 support which allows browsers to fetch resources more efficiently.

Maybe mention, that it's (kind of) 'last gen'?

**Comment by KeenRivals** [comment]
It's a good thought but I don't think nginx, apache, or any other mainstream server has native support for HTTP/3. [Client support is still bad too](https://caniuse.com/?search=http3). I think this will be worth revisiting once servers and clients catch up. I know I'm looking forward to it.

Funny enough I have http3 enabled for this site at Cloudflare but at least with Firefox I can't get it to run over http3. This [random checker I found doesn't indicate http3 either](https://www.http3check.net/?host=bestmotherfucking.website#).

**Comment by JacksonChen666** [comment]
@KeenRivals it's been closer to 2 years now, [client support appears to be better](https://caniuse.com/http3), [the check says http3 supported](https://www.http3check.net/?host=bestmotherfucking.website) (but can't get firefox to run over http3 unless i make `network.http.http3.enabled` `true` in `about:config`), [most things already have it too](https://en.wikipedia.org/wiki/HTTP/3#Implementations)

however, i wasn't able to get anything noticeable like how fast the requests are, other than http3.

anyways, i guess this issue could've been closed anyways because @KeenRivals said that http3 was enabled already and i guess that's what the author wanted

**Comment by jtagcat** [comment]
It was 1.5y ago, a different person practically. I didn't care and I care less now :)

**Comment by KeenRivals** [comment]
I'm pretty sure nginx and apache still don't support http3 out of the box
anyways. ☹️
