### ISSUE TITLE
Meme headers

### ISSUE THREAD

**Issue by Seirdy** [KeenRivals/bestmotherfucking.website#61]
bestmotherfucking.website should recommend and use some meme headers:

- `Content-Security-Policy` can ensure that your webpage only contains approved content, and doesn't have any webshit. Relevant to the HTTPS section is the `upgrade-insecure-requests` directive, or `block-all-mixed-content`.
- `referrer-policy` protects users' privacy when they click your links
- `cache-control` is already covered
- `strict-transport-security` as part of "You have no excuse for using HTTP".

There are others I'd recommend (x-content-type-options, cross-origin headers, and maybe permission-policy), but this isn't meant to be some comprehensive guide. Maybe link to another page that explains headers in more detail for those more inclined to learn more.

**Comment by jtagcat** [comment]
HSTS +1, but configuring comes from many different places, and doesn't directly make a website noticeably less shit.

referrer-policy is kind of out of scope, user's browsers might do this. As a (say indie) website receiving traffic, it does be neet to know where it came from. There are other, and overall too many gotchas for it to be short, on-point, and fitting (not wasting the length) on the webpage.

Content-Security-Policy: if you can word it well, I guess ok.

@KeenRivals there are many nice to have, but kinda out of scope things, I'd propose, that it might be a good idea to include the main points, plain (no 'read more here'), and last point with a long 'if you really want to' pointing to a page with a list(/extension) of nice-to-haves.

At the same time, if it is not worth the main page, it probably doesn't have a place on the secondary page. Thus, I unpropose the idea, take that back.

It might be a good idea to include an issue template with a paragraph of 'this is a statement of the most dumb things, in no way complete or a flowchart how-what to exactly do, write your own site, and maybe this page will link to it later', etc (what I have expressed in previous comments)

**Comment by jtagcat** [comment]
(not directed at this issue/author)

There is a lot of drive-by 'here is my cents' (what I used to do few years ago, have seen it may be harmful, and since tried to curb) and bike shedding, feeding on notification subscriptions. Most of them don't result to much.

**Comment by KeenRivals** [comment]
It's funny I was just thinking about setting a CSP on this site to block *everything* just because.

I have mixed feelings on this. It's kind of in the weeds, and I don't see failure or adherence to these as things that make websites bad in the same way that not using caching, https, or compression do. I think HSTS is going to get interesting as browsers move to prefer HTTPS-only on their own, but will still be important.

Rather than separate headings for each point I think it'd make more sense to put them under a site security thing, but I think having a watered down catch-all section would kind of take away some of the punch.

Upgrade-insecure-requests and mixed content are kind of self-created problems, no? If your site is referring to stuff over an insecure scheme that should be fixed. I feel like upgrade-insecure-requests is a band-aid for huge sites that need large rewrites to do it correctly.

I like referrer-policy and think it has its uses. But I'm not sure it's so cut and dry. [Firefox's and Chrome's default is strict-origin-when-cross-origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy), which sends only the domain on cross-site requests. I think that is a very good default. If I were concerned about hiding my origin I could use the policy to control that. 

Overall I can't think of an easy way to work these into the site so I'll leave them out at least until then.

**Comment by Seirdy** [comment]
On Tue, Feb 15, 2022 at 06:09:17AM -0800, KeenRivals wrote:
>It's funny I was just thinking about setting a CSP on this site to block *everything* just because.

This CSP should do the trick:

content-security-policy: default-src 'none'; style-src 'sha256-SHA256_OF_YOUR_INLINE_CSS'; style-src-attr 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'; upgrade-insecure-requests; navigate-to 'none'; sandbox

That should block basically everything except the page. If you want to 
allow script injection, e.g. from addons, then replace "sandbox" with 
"sandbox allow-same-origin".

>Upgrade-insecure-requests and mixed content are kind of self-created 
>problems, no? If your site is referring to stuff over an insecure 
>scheme that should be fixed. I feel like upgrade-insecure-requests is a 
>band-aid for huge sites that need large rewrites to do it correctly.

A content security policy is a form of defense-in-depth. Yes, you should fix your mistakes, but you should have an second layer of protection if/when your existing approach fails.

See https://en.wikipedia.org/wiki/Defense_in_depth_(computing)

>Overall I can't think of an easy way to work these into the site so 
>I'll leave them out at least until then.

That's fair. Maybe a deprecating statement like "since your useless ass 
can't do anything right, throw in a CSP for when you fuck up and forget 
the 's' on a URL's scheme."


-- 
/Seirdy

**Comment by KeenRivals** [comment]
Thanks for that example CSP! As I was digging into it, it looked pretty
intense. What you provided gives me a great starting point!

**Comment by KeenRivals** [comment]
We've got a CSP now that's based on what you provided. I had some trouble with the inline style. Despite following a few articles around I couldn't figure out how to generate the CSP before deploying after making style changes. I suspect it's some kind of whitespace issue.
